[workspace]
members = [
    "logion-shared",
    "pallet-lo-authority-list",
    "pallet-logion-loc",
    "pallet-logion-vault",
    "pallet-logion-vote",
    "pallet-verified-recovery"
]
[profile.release]
panic = "unwind"
